package FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, 2 August, 2020 4:18:13 PM EDT
*/

public interface FrontEndOperations 
{
  String createPlayerAccount (String firstName, String lastName, String age, String username, String password, String ipAddress);
  String playerSignIn (String username, String password, String ipAddress);
  String playerSignOut (String username, String ipAddress);
  String transferAccount (String username, String password, String oldIpAddress, String newIpAddress);
  String getPlayerStatus (String ipAddress);
  String suspendAccount (String usernameToSuspend, String ipAddress);
} // interface FrontEndOperations
