package FrontEndApp;


/**
* FrontEndApp/FrontEndPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEnd.idl
* Sunday, 2 August, 2020 4:18:13 PM EDT
*/

public abstract class FrontEndPOA extends org.omg.PortableServer.Servant
 implements FrontEndApp.FrontEndOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createPlayerAccount", new java.lang.Integer (0));
    _methods.put ("playerSignIn", new java.lang.Integer (1));
    _methods.put ("playerSignOut", new java.lang.Integer (2));
    _methods.put ("transferAccount", new java.lang.Integer (3));
    _methods.put ("getPlayerStatus", new java.lang.Integer (4));
    _methods.put ("suspendAccount", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // FrontEndApp/FrontEnd/createPlayerAccount
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String age = in.read_string ();
         String username = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.createPlayerAccount (firstName, lastName, age, username, password, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // FrontEndApp/FrontEnd/playerSignIn
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.playerSignIn (username, password, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // FrontEndApp/FrontEnd/playerSignOut
       {
         String username = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.playerSignOut (username, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // FrontEndApp/FrontEnd/transferAccount
       {
         String username = in.read_string ();
         String password = in.read_string ();
         String oldIpAddress = in.read_string ();
         String newIpAddress = in.read_string ();
         String $result = null;
         $result = this.transferAccount (username, password, oldIpAddress, newIpAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // FrontEndApp/FrontEnd/getPlayerStatus
       {
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.getPlayerStatus (ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // FrontEndApp/FrontEnd/suspendAccount
       {
         String usernameToSuspend = in.read_string ();
         String ipAddress = in.read_string ();
         String $result = null;
         $result = this.suspendAccount (usernameToSuspend, ipAddress);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:FrontEndApp/FrontEnd:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public FrontEnd _this() 
  {
    return FrontEndHelper.narrow(
    super._this_object());
  }

  public FrontEnd _this(org.omg.CORBA.ORB orb) 
  {
    return FrontEndHelper.narrow(
    super._this_object(orb));
  }


} // class FrontEndPOA
