package GameServerApp;


/**
* GameServerApp/GameServerOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Sunday, 21 June, 2020 12:59:20 AM EDT
*/

public interface GameServerOperations 
{
  String createPlayerAccount (String firstName, String lastName, String age, String username, String password, String ipAddress);
  String playerSignIn (String username, String password);
  String playerSignOut (String username);
  String transferAccount (String username, String password, String newIpAddress);
  String getPlayerStatus ();
  String suspendAccount (String usernameToSuspend);
} // interface GameServerOperations
