package GameServerApp;


/**
* GameServerApp/GameServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from GameServer.idl
* Sunday, 21 June, 2020 12:59:20 AM EDT
*/

public interface GameServer extends GameServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface GameServer
