
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "GameServer", targetNamespace = "http://interfaces/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface GameServer {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createPlayerAccount", targetNamespace = "http://interfaces/", className = "client.CreatePlayerAccount")
    @ResponseWrapper(localName = "createPlayerAccountResponse", targetNamespace = "http://interfaces/", className = "client.CreatePlayerAccountResponse")
    @Action(input = "http://interfaces/GameServer/createPlayerAccountRequest", output = "http://interfaces/GameServer/createPlayerAccountResponse")
    public String createPlayerAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignOut", targetNamespace = "http://interfaces/", className = "client.PlayerSignOut")
    @ResponseWrapper(localName = "playerSignOutResponse", targetNamespace = "http://interfaces/", className = "client.PlayerSignOutResponse")
    @Action(input = "http://interfaces/GameServer/playerSignOutRequest", output = "http://interfaces/GameServer/playerSignOutResponse")
    public String playerSignOut(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "playerSignIn", targetNamespace = "http://interfaces/", className = "client.PlayerSignIn")
    @ResponseWrapper(localName = "playerSignInResponse", targetNamespace = "http://interfaces/", className = "client.PlayerSignInResponse")
    @Action(input = "http://interfaces/GameServer/playerSignInRequest", output = "http://interfaces/GameServer/playerSignInResponse")
    public String playerSignIn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPlayerStatus", targetNamespace = "http://interfaces/", className = "client.GetPlayerStatus")
    @ResponseWrapper(localName = "getPlayerStatusResponse", targetNamespace = "http://interfaces/", className = "client.GetPlayerStatusResponse")
    @Action(input = "http://interfaces/GameServer/getPlayerStatusRequest", output = "http://interfaces/GameServer/getPlayerStatusResponse")
    public String getPlayerStatus();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferAccount", targetNamespace = "http://interfaces/", className = "client.TransferAccount")
    @ResponseWrapper(localName = "transferAccountResponse", targetNamespace = "http://interfaces/", className = "client.TransferAccountResponse")
    @Action(input = "http://interfaces/GameServer/transferAccountRequest", output = "http://interfaces/GameServer/transferAccountResponse")
    public String transferAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "suspendAccount", targetNamespace = "http://interfaces/", className = "client.SuspendAccount")
    @ResponseWrapper(localName = "suspendAccountResponse", targetNamespace = "http://interfaces/", className = "client.SuspendAccountResponse")
    @Action(input = "http://interfaces/GameServer/suspendAccountRequest", output = "http://interfaces/GameServer/suspendAccountResponse")
    public String suspendAccount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
